bidb/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.views.static import serve


urlpatterns = (
    url(r'', include('bidb.api.urls', namespace='api')),
    url(r'', include('bidb.buildinfo.urls', namespace='buildinfo')),
    url(r'', include('bidb.packages.urls', namespace='packages')),
    url(r'', include('bidb.static.urls', namespace='static')),
)

if settings.DEBUG:
    urlpatterns += (
        url(
            r'^storage/(?P<path>.*)$',
            serve,
            {'document_root': settings.MEDIA_ROOT},
        ),
    )

bidb/buildinfo/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone


class Buildinfo(models.Model):
    sha1 = models.CharField(max_length=40, unique=True)

    source = models.ForeignKey(
        'packages.Source', related_name='buildinfos', on_delete=models.CASCADE
    )

    architecture = models.ForeignKey(
        'packages.Architecture',
        related_name='buildinfos',
        on_delete=models.CASCADE,
    )
    version = models.CharField(max_length=200)

    build_path = models.CharField(max_length=512)
    build_date = models.DateTimeField(null=True)
    build_origin = models.ForeignKey(
        'Origin', null=True, on_delete=models.CASCADE
    )
    build_architecture = models.ForeignKey(
        'packages.Architecture',
        related_name='buildinfos_build',
        on_delete=models.CASCADE,
    )

    environment = models.TextField()

    created = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ('-created',)
        get_latest_by = 'created'

    def __str__(self):
        return u"pk=%d source=%r version=%r" % (
            self.pk,
            self.source,
            self.version,
        )

    def get_absolute_url(self):
        return reverse('buildinfo:view', args=(self.sha1, self.get_filename()))

    def get_absolute_raw_url(self):
        return reverse(
            'buildinfo:raw-text', args=(self.sha1, self.get_filename())
        )

    def get_filename(self):
        return '{}_{}_{}'.format(
            self.source.name,
            self.version,
            self.architecture.name.split(' ')[0],
        )

    def get_storage_name(self):
        return 'buildinfo.Buildinfo/{}/{}/{}'.format(
            self.sha1[:2], self.sha1[2:4], self.sha1
        )


class Binary(models.Model):
    buildinfo = models.ForeignKey(
        Buildinfo, related_name='binaries', on_delete=models.CASCADE
    )

    binary = models.ForeignKey(
        'packages.Binary',
        related_name='generated_binaries',
        on_delete=models.CASCADE,
    )

    created = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ('binary__name',)
        get_latest_by = 'created'
        unique_together = (('buildinfo', 'binary'),)

    def __str__(self):
        return u"pk=%d binary=%r" % (self.pk, self.binary)


class Checksum(models.Model):
    """
    Not the same as Binary as we could potentially have a Checksum for a
    Binary, etc.
    """

    buildinfo = models.ForeignKey(
        Buildinfo, related_name='checksums', on_delete=models.CASCADE
    )

    filename = models.CharField(max_length=255)
    size = models.IntegerField()

    checksum_md5 = models.CharField(max_length=100)
    checksum_sha1 = models.CharField(max_length=100)
    checksum_sha256 = models.CharField(max_length=100)

    binary = models.OneToOneField(
        Binary, null=True, related_name='checksum', on_delete=models.CASCADE
    )

    created = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ('-created',)
        get_latest_by = 'created'
        unique_together = (('buildinfo', 'filename'),)

    def __str__(self):
        return "pk={} filename={!r}".format(self.pk, self.filename)


class Origin(models.Model):
    name = models.CharField(max_length=255)

    created = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ('name',)
        get_latest_by = 'created'

    def __str__(self):
        return "pk={} name=%r".format(self.pk, self.name)

templates/base/base.html
{% extends "base/generic_base.html" %}

{% block body %}

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url "static:landing" %}">
        buildinfo.debian.net
      </a>
    </div>
    <div class="collapse navbar-collapse" id="navbar-collapse">
      <ul class="nav navbar-nav">
        <li><a href="{% url "packages:sources" %}">Sources</a></li>
        <li><a href="{% url "packages:binaries" %}">Binaries</a></li>
      </ul>
    </div>
  </div>
</nav>

{% if messages %}
{% for message in messages %}
<div class="container alert alert-{% if message.tags == "error" %}danger {% else %}{{ message.tags }}{% endif %}">
  <button type="button" class="close" data-dismiss="alert">×</button>
  {{ message }}
</div>
{% endfor %}
{% endif %}

{% block container %}
<div class="container">
  {% block content %}{% endblock %}
</div>
{% endblock %}

<footer>
  <div class="container">
    <hr>
    <p class="text-muted text-center">
      Copyright &copy; 2015&mdash;2016
      <a href="https://chris-lamb.co.uk">Chris Lamb</a>.
      Released under the terms of the
      <a href="https://www.gnu.org/licenses/agpl-3.0.en.html">GNU Affero General Public License</a>.
      <a href="https://salsa.debian.org/reproducible-builds/buildinfo.debian.net">Source</a>.
    </p>

    <p class="text-muted text-center">
      Hardware sponsored by:
      <a href="https://m.do.co/c/494f892a988b"><img src="{% static "images/digitalocean.png" %}"></a>
    </p>
  </div>
</footer>

{% endblock %}

templates/base/generic_base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>{% block title %}buildinfo.debian.net{% endblock %}</title>

  {% block css %}
  <link href="{% static "css/bootstrap.css" %}" rel="stylesheet" />
  <link href="{% static "css/bidb.css" %}" rel="stylesheet" media="screen" />
  {% endblock %}

  {% block extrahead %}{% endblock %}
</head>
<body class="{% block body_classes %}{% endblock %}">
  {% block body %}{% endblock %}

  {% block js %}
  <script src="{% static "js/jquery.js" %}"></script>
  <script src="{% static "js/bootstrap.js" %}"></script>
  {% endblock %}
</body>
</html>